box_name: centos/7
#box_url:
box_hostname: devstackcentos7
vm_memory: 8192
vm_cpus: 4
internal1_ip: 172.20.1.11
internal1_netmask: 255.255.255.0
external1_ip: 172.20.2.1
external1_netmask: 255.255.255.0
vm_forward_port: 80
host_forward_port: 8080
