---
- hosts: default
  vars_files:
    - vars.yml
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: sudo apt-get -y install python-minimal

  tasks:
    - name: create keyring config directory
      file: >
        state=directory
        dest={{ keyring_config_dir }}

    - name: change file ownership, group and mode
      file: >
        path={{ devstack_path }}
        state=directory
        mode=0755
        owner={{ devstack_user }}
        group={{ devstack_user }}
        recurse=yes
      become: True

    - name: copy keyring config file to workaround https://bugs.launchpad.net/bugs/1242992
      copy: >
        src=files/keyringrc.cfg
        dest={{ keyring_config_dir }}/keyringrc.cfg

    - name: install git
      apt: "name=git update_cache=yes"
      become: True

    - name: checkout devstack
      git: repo={{ devstack_repo }} dest={{ devstack_path }} version={{ devstack_branch }} accept_hostkey=yes

    - name: local.conf
      template: src={{ local_conf_path }} dest={{ devstack_path }}/local.conf

    - name: source openrc in profile
      lineinfile: dest=/home/{{ devstack_user }}/.profile regexp=".*openrc" line='. {{ devstack_path }}/openrc'

    - name: enable external interface
      command: ip link set dev {{ external_interface }} up
      become: True

    #- name: add port to br-ex bridge
    #  shell: /usr/bin/ovs-vsctl add-port br-ex {{ external_interface }}
    #  become: True

    #- name: destroy default network of libvirt
    #  shell: /usr/bin/virsh net-destroy default
    #  become: True
